version: '2'
services:
  web:
    build: 
      context: .
      dockerfile: "./docker/node.dockerfile"
    depends_on:
      - mysql
    volumes:
      - ./:/usr/app
    expose:
      - 3000
    ports:
      - "3000:3000"
    command: npm run dev
  mysql:
    build:
      context: .
      dockerfile: "./docker/mysql.dockerfile"
